name: Docker Actions Workflow

on:
  pull_request:
    types: [labeled]

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: hello-action
        uses: ./.github/actions/hello-world
      
      - name: cat-facts
        uses: ./.github/actions/cat-facts